"""Connect a project to Loop for one or more hosts.

- ``claude``  : .mcp.json server entry + .claude/skills/loop/SKILL.md (+ optional status line)
- ``codex``   : .codex/config.toml server table + .agents/skills/loop/SKILL.md
- ``generic`` : a managed section in AGENTS.md (read by Codex, Cursor, Gemini CLI, Aider, ...)

Every host also gets ``.loop/bin/loop`` (a CLI wrapper) and the visible
``.loop/STATUS.md``. Existing user content is preserved; only managed entries change.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import shlex
import stat
import sys

from .adapters import mcp_server_spec
from .store import Project
from .util import LoopError, atomic_write, read_json, write_json

TEMPLATE = Path(__file__).parent / "templates" / "SKILL.md"
BEGIN, END = "# >>> loop-engineering (managed) >>>", "# <<< loop-engineering (managed) <<<"
MD_BEGIN, MD_END = "<!-- >>> loop-engineering (managed) >>> -->", "<!-- <<< loop-engineering (managed) <<< -->"
HOSTS = ("claude", "codex", "generic")
LEGACY_SERVERS = ("loop-native",)
LEGACY_SKILLS = (".agents/skills/loop-engineering", ".claude/skills/loop-engineering")


def install(project: Project, hosts: list[str], statusline: bool = False) -> dict:
    unknown = set(hosts) - set(HOSTS)
    if unknown:
        raise LoopError(f"Unknown hosts {sorted(unknown)}; choose from {HOSTS}")
    project.ensure()
    changed = [_cli_wrapper(project)]
    ignore = project.loop / ".gitignore"
    if "bin/" not in ignore.read_text():
        atomic_write(ignore, ignore.read_text() + "bin/\n")
    skill = TEMPLATE.read_text(encoding="utf-8")
    if "claude" in hosts:
        changed.append(_claude_mcp(project))
        changed.append(_write(project.root / ".claude/skills/loop/SKILL.md", skill))
        if statusline:
            changed.append(_claude_statusline(project))
    if "codex" in hosts:
        changed.append(_codex_config(project))
        changed.append(_write(project.root / ".agents/skills/loop/SKILL.md", skill))
    if "generic" in hosts:
        changed.append(_agents_md(project))
    return {"project": str(project.root), "hosts": hosts, "changed": [c for c in changed if c],
            "next": "Reload MCP servers in your tool (restart the session or run /mcp), then ask it to use the "
                    "loop skill. Status: .loop/STATUS.md · `.loop/bin/loop status --watch` · "
                    "`.loop/bin/loop dashboard`."}


def _write(path: Path, content: str) -> str | None:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return None
    atomic_write(path, content)
    return str(path)


def _cli_wrapper(project: Project) -> str | None:
    package_root = Path(__file__).resolve().parent.parent
    script = ("#!/bin/sh\n# Loop Engineering CLI for this project (generated by `loop install`).\n"
              f"PYTHONPATH={shlex.quote(str(package_root))}${{PYTHONPATH:+:$PYTHONPATH}} "
              f"exec {shlex.quote(sys.executable)} -m loop_engineering --project "
              f"{shlex.quote(str(project.root))} \"$@\"\n")
    path = project.loop / "bin" / "loop"
    result = _write(path, script)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return result


def _claude_mcp(project: Project) -> str | None:
    path = project.root / ".mcp.json"
    data = read_json(path, {}) if path.exists() else {}
    if not isinstance(data, dict):
        raise LoopError(f"{path} is not a JSON object; fix it before installing")
    servers = data.setdefault("mcpServers", {})
    for legacy in LEGACY_SERVERS:
        servers.pop(legacy, None)
    spec = mcp_server_spec(project.root, autonomous=False)
    if servers.get("loop") == spec:
        return None
    servers["loop"] = spec
    write_json(path, data)
    return str(path)


def _claude_statusline(project: Project) -> str | None:
    path = project.root / ".claude" / "settings.local.json"
    data = read_json(path, {}) if path.exists() else {}
    command = str(project.loop / "bin" / "loop") + " statusline"
    current = data.get("statusLine")
    if current and current.get("command") != command:
        raise LoopError(f"{path} already has a statusLine; add `{command}` to it yourself")
    if current:
        return None
    data["statusLine"] = {"type": "command", "command": command, "padding": 0}
    write_json(path, data)
    return str(path)


def _toml_value(value) -> str:
    if isinstance(value, list):
        return "[" + ", ".join(json.dumps(v) for v in value) + "]"
    return json.dumps(value)


def _codex_config(project: Project) -> str | None:
    path = project.root / ".codex" / "config.toml"
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    text = remove_managed(original, BEGIN, END)
    for legacy in LEGACY_SERVERS + ("loop",):
        text = remove_toml_table(text, f"mcp_servers.{legacy}")
    spec = mcp_server_spec(project.root, autonomous=False)
    block = "\n".join([BEGIN, "[mcp_servers.loop]", f"command = {_toml_value(spec['command'])}",
                       f"args = {_toml_value(spec['args'])}", "tool_timeout_sec = 180", "startup_timeout_sec = 30",
                       'default_tools_approval_mode = "approve"',  # controller-bounded tools; no per-call prompts
                       "", "[mcp_servers.loop.env]",
                       *[f"{k} = {_toml_value(v)}" for k, v in spec["env"].items()], END, ""])
    result = (text.rstrip() + "\n\n" if text.strip() else "") + block
    if result == original:
        return None
    atomic_write(path, result)
    return str(path)


def _agents_md(project: Project) -> str | None:
    path = project.root / "AGENTS.md"
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    body = "\n".join([MD_BEGIN, "## Loop Engineering", "",
                      "This project runs goals through a Loop controller. Current status: `.loop/STATUS.md`.",
                      "Use the `loop` MCP tools if your tool supports MCP (see `.mcp.json`); otherwise use the CLI "
                      "`.loop/bin/loop` (`next`, `plan`, `task done`, `check`, `note`, `ask`, `finish`, `status`).",
                      "Start each turn with `loop next`, record a handoff note before you stop, never edit `.loop/` "
                      "by hand, and never weaken checks. Full guide: `.agents/skills/loop/SKILL.md` or "
                      "`.claude/skills/loop/SKILL.md`.", MD_END, ""])
    text = remove_managed(original, MD_BEGIN, MD_END)
    result = (text.rstrip() + "\n\n" if text.strip() else "") + body
    if result == original:
        return None
    atomic_write(path, result)
    return str(path)


def remove_managed(text: str, begin: str, end: str) -> str:
    while begin in text and end in text:
        start = text.index(begin)
        stop = text.index(end, start) + len(end)
        text = text[:start].rstrip("\n") + "\n" + text[stop:].lstrip("\n")
    return text


def remove_toml_table(text: str, name: str) -> str:
    """Remove ``[name]`` and its ``[name.*]`` sub-tables (line based, preserves the rest)."""
    out, skipping = [], False
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("[") and not stripped.startswith("[["):
            header = stripped.strip("[]").strip()
            skipping = header == name or header.startswith(name + ".")
        if not skipping:
            out.append(line)
    return "".join(out)


def uninstall_legacy(project: Project) -> list[str]:
    """Remove v1 host entries (the loop-native MCP server and its skill)."""
    removed = []
    codex = project.root / ".codex" / "config.toml"
    if codex.exists():
        text = codex.read_text(encoding="utf-8")
        cleaned = text
        for legacy in LEGACY_SERVERS:
            cleaned = remove_toml_table(cleaned, f"mcp_servers.{legacy}")
        if cleaned != text:
            atomic_write(codex, cleaned)
            removed.append(str(codex))
    mcp = project.root / ".mcp.json"
    if mcp.exists():
        data = read_json(mcp, {})
        if any(name in data.get("mcpServers", {}) for name in LEGACY_SERVERS):
            for name in LEGACY_SERVERS:
                data["mcpServers"].pop(name, None)
            write_json(mcp, data)
            removed.append(str(mcp))
    return removed


def statusline_from_stdin(stdin) -> str:
    """Claude Code status line: reads the session JSON on stdin to find the project."""
    from .status import line
    try:
        data = json.loads(stdin.read() or "{}")
    except (json.JSONDecodeError, OSError):
        data = {}
    start = (data.get("workspace") or {}).get("current_dir") or data.get("cwd") or os.getcwd()
    try:
        project = Project.find(start)
        return line(project.goal())
    except Exception:
        return "loop: no goal"
